version: "3"

services:
  ontime:
    container_name: ontime
    image: tim/ontime:latest
    ports:
      - "4001:4001/tcp"
      - "8888:8888/udp"
      - "9999:9999/udp"
    volumes:
      - "./ontime-db:/external/db/"
    environment:
      - TZ=America/New_York
    restart: unless-stopped
