version: "3"

services:
  ontime:
    container_name: ontime
    image: ontime_tim:latest 
    ports:
      - "4001:4001/tcp"
      - "127.0.0.1:8888:8888/udp"
    volumes:
      - "./ontime-db:/server/preloaded-db"
      - "./ontime-external:/server/external"
    environment:
      - TZ=America/New_York
    restart: unless-stopped
